name: Debug Windows

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-reusable
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  build_windows:
    name: >-
      Windows
      ${{ fromJSON(matrix.free-threading) && '(free-threading)' || '' }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        arch:
          - x64
        free-threading:
          - true
    uses: ./.github/workflows/reusable-windows.yml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      free-threading: ${{ matrix.free-threading }}
