on:
  workflow_call:
    inputs:
      config_hash:
        required: true
        type: string
      free-threading:
        required: false
        type: boolean
        default: false

jobs:
  build_macos:
    name: 'build and test'
    timeout-minutes: 60
    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
      PYTHONSTRICTEXTENSIONBUILD: 1
    strategy:
      fail-fast: false
      matrix:
        os: [
          "macos-14",  # M1
          "macos-13",  # Intel
        ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Runner image version
      run: echo "IMAGE_VERSION=${ImageVersion}" >> $GITHUB_ENV
    - name: Restore config.cache
      uses: actions/cache@v4
      with:
        path: config.cache
        key: ${{ github.job }}-${{ matrix.os }}-${{ env.IMAGE_VERSION }}-${{ inputs.config_hash }}
    - name: Configure ccache action
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        # save: ${{ github.event_name == 'push' }}
        key:  ${{ github.job }}-${{ matrix.os }}-${{ inputs.free-threading }}
        max-size: "50M"
    - name: Add ccache to PATH
      run: |
        echo "PATH=/opt/homebrew/opt/ccache/libexec:/usr/local/opt/ccache/libexec:$PATH" >> $GITHUB_ENV
        ls -al /opt/homebrew/opt/ccache/libexec || true
        ls -al /usr/lib/ccache || true
        ls -al /usr/local/opt/ccache/libexec || true
    - name: Install Homebrew dependencies
      run: brew install pkg-config openssl@3.0 xz gdbm tcl-tk
    - name: Configure CPython
      run: |
        GDBM_CFLAGS="-I$(brew --prefix gdbm)/include" \
        GDBM_LIBS="-L$(brew --prefix gdbm)/lib -lgdbm" \
        ./configure \
          --config-cache \
          --with-pydebug \
          ${{ inputs.free-threading && '--disable-gil' || '' }} \
          --prefix=/opt/python-dev \
          --with-openssl="$(brew --prefix openssl@3.0)"
        which gcc
    - name: Build CPython
      run: make -j4
    - name: Display build info
      run: make pythoninfo
    # - name: Tests
    #   run: make test
